### ISSUE TITLE
Feature Request: Output results to build/reports

### ISSUE THREAD

**Issue by Thunderforge** [aalmiray/jdeps-gradle-plugin#1]
I tried running this on one of my smaller projects and wound up with 210 lines of console output. I imagine that my larger projects will be even larger.

I would like to have this plugin output to `build/reports`, the standard location for Gradle reports (used by the PMD plugin, Java unit tests, etc). I would be fine with it either outputting all the time or optionally outputting as a configuration option.

**Comment by aalmiray** [comment]
This would be a good addition to the plugin indeed. We'll work on it this week and hopefully push a  new release soon 😄
