### ISSUE TITLE
Feature request: allow passing arbitrary options to jdeps

### ISSUE THREAD

**Issue by kstarsinic** [aalmiray/jdeps-gradle-plugin#15]
To future-proof and to support various implementations, I'd like to be able to pass arbitrary options to jdeps , e.g., --api-only or --dot-output, via the plugin.

**Comment by aalmiray** [comment]
That may be a challenge as currently all options are defined as task properties, thus they must explicitly exist in code. Though the plugin could be update at least every 6 months if there are new flags available on the latest `jdeps` tool.

**Comment by ennioVisco** [comment]
Well it could make sense to at least support these popular flags maybe
