### ISSUE TITLE
Support the --print-module-deps argument

### ISSUE THREAD

**Issue by otrosien** [aalmiray/jdeps-gradle-plugin#20]
This parameter is helpful as input to building a reduced JRE with `jlink`.

**Comment by aalmiray** [comment]
Where should the output go? Gradle does not support String properties as output. The list of modules would have to be written to a file.

**Comment by aalmiray** [comment]
Available in `0.17.0`.

**Comment by otrosien** [comment]
wow, thanks alot, that was unexpectedly fast. I looked at the PR and just found one small nit. it's dependencies, not dependences. 👍🏼

**Comment by aalmiray** [comment]
I thought so as well but that's the actual text lifted from `jdeps -h` 🤷‍♂️
