### ISSUE TITLE
Upgrade Gradle Wrapper to 4.x

### ISSUE THREAD

**Issue by Thunderforge** [aalmiray/jdeps-gradle-plugin#6]
The current Gradle wrapper for the project is 3.5, which is incompatible with JDK 10. Building the project means that the user has to switch to an older version of Java.

I tried to upgrade the wrapper myself, but trying 4.0 or later gave me the following error:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/Will/OpenSource/jdeps-gradle-plugin/build.gradle' line: 61

* What went wrong:
A problem occurred evaluating root project 'jdeps-gradle-plugin'.
> java.lang.NullPointerException (no error message)
```

[Line 61](https://github.com/aalmiray/jdeps-gradle-plugin/blob/master/build.gradle#L61) contains this code: `compile files(org.gradle.internal.jvm.Jvm.current().toolsJar)`. It looks like the internal implementation has changed.

I'm not entirely sure what it's doing, but regardless, it doesn't work on Gradle 4.x.

**Comment by aalmiray** [comment]
Fixed with https://github.com/aalmiray/jdeps-gradle-plugin/commit/04a4b8578d0e32ec5ed6899681494eee7cd885cb
